// Maps a quick-entry text + parsed macros into a nutrition_logs insert
// payload. Mirrors outbox/mapSetLog.ts's isValid*/to*Insert pairing.
//
// `id` is generated by the caller (expo-crypto's randomUUID), not in here —
// keeps this module native-module-free, same reasoning as workout/session.ts:
// expo-crypto transitively pulls in react-native's Flow-typed sources, which
// plain Node/Vitest can't parse.

import type { NutritionLogInsert } from './types';
import { hasAnyMacro, parseQuickEntry, type ParsedMacros } from './parseQuickEntry';

export function toNutritionLogInsert(
  id: string,
  userId: string,
  description: string,
  parsed: ParsedMacros = parseQuickEntry(description),
): NutritionLogInsert {
  return {
    id,
    user_id: userId,
    method: 'TYPED',
    description: description.trim() || null,
    protein_g: parsed.protein_g,
    carbs_g: parsed.carbs_g,
    fat_g: parsed.fat_g,
    calories: parsed.calories,
  };
}

export { hasAnyMacro, parseQuickEntry };
