// Pure builders for client-side workout sessions. The session row is created
// client-first (UUID) so offline logging can reference it before it syncs.
//
// The random id is generated by the caller (expo-crypto's randomUUID), not
// in here — keeps this module free of native-module imports, which matters
// because expo-crypto transitively pulls in react-native's Flow-typed
// sources that plain Node/Vitest can't parse.

import type { WorkoutSessionInsert } from '../outbox/types';

export interface SessionDraft {
  id: string;
  userId: string;
  sessionName: string;
  startedAtMs: number;
}

export function createSessionDraft(
  userId: string,
  sessionName: string,
  nowMs: number = Date.now(),
  id: string,
): SessionDraft {
  return { id, userId, sessionName, startedAtMs: nowMs };
}

/** Build the insert payload with duration measured from draft start to now. */
export function sessionInsertFrom(
  draft: SessionDraft,
  nowMs: number = Date.now(),
  templateId: string | null = null,
): WorkoutSessionInsert {
  return {
    id: draft.id,
    user_id: draft.userId,
    template_id: templateId,
    session_name: draft.sessionName,
    completed_at: new Date(nowMs).toISOString(),
    duration_seconds: Math.max(0, Math.round((nowMs - draft.startedAtMs) / 1000)),
  };
}
